@startuml BBショップドメインモデル図
skinparam componentStyle rectangle

' ユーザ
' ユーザID、名前、住所、電話番号、メールアドレス
[ユーザ] o-- [ユーザID]
[ユーザ] o-- [名前]
[ユーザ] o-- [住所]
[ユーザ] o-- [電話番号]
[ユーザ] o-- [メールアドレス]
[ユーザ] o-- [注文]
[ユーザ] o-- [返品]
[ユーザ] o-- [決済]
' 商品
' 商品ID、タイトル、価格、在庫数
[商品] o-- [商品ID]
[商品] o-- [タイトル]
[商品] o-- [価格]
[商品] o-- [在庫数]
' 注文
' 注文ID、数量、注文日、配送先、注文状態
[注文] o-- [注文ID]
[注文] o-- [ユーザ]
[注文] o-- [商品]
[注文] o-- [数量]
[注文] o-- [注文日]
[注文] o-- [配送先]
[注文] o-- [注文状態]
' 決済
' 決済ID、決済方法、金額、決済結果
[決済] o-- [決済ID]
[決済] o-- [決済方法]
[決済] o-- [金額]
[決済] o-- [決済結果]
' 発送
' 発送ID、配送先、発送日、発送状況
[発送] o-- [発送ID]
[発送] o-- [配送先]
[発送] o-- [発送日]
[発送] o-- [発送状況]
' 返品
' 返品ID、返品理由、返品受付日、返金状態
[返品] o-- [返品ID]
[返品] o-- [返品理由]
[返品] o-- [返品受付日]
[返品] o-- [返金状態]
' 管理者
' 管理者ID、名前、権限
[管理者] o-- [管理者ID]
[管理者] o-- [名前]
[管理者] o-- [権限]
@enduml