@startuml .
skinparam classAttributeIconSize 0
class agenda {
-ユーザID
-名前
-予約番号
-ユーザ名
-会議の目的
-会議室情報
-会議室名
-座席数
-AV機器の有無
+ログインする()
+ログアウトする()
+指定の日付の予約済会議室の表示()
+新しい予約の作成()
+予約の変更()
+予約の取り消し()
}
@enduml
