@startuml Web訪問者システムドメインモデル図
skinparam componentStyle rectangle

[会議室予約情報] o-- [会議室名]
[会議室予約情報] o-- [会議開始時刻]
[会議室予約情報] o-- [会議終了時刻]
[会議室予約情報] o-- [座席数]
[会議室予約情報] o-- [AV機器の有無]
[会議室予約情報] o-- [名前]
[会議室予約情報] o-- [ユーザID]
[会議室予約情報] o-- [ユーザ名]
[会議室予約情報] o-- [会議の目的]


[ユーザ情報] o-- [名前]
[ユーザ情報] o-- [ユーザID]

[会議室情報] o-- [会議室名]
[会議室情報] o-- [座席数]
[会議室情報] o-- [AV機器の有無]


@endl