@startuml Web訪問者システムユースケース図
left to right direction
actor 訪問者 as U1

rectangle Web訪問者システム as WVS {
  usecase "訪問者登録" as UC1
  usecase "訪問者情報参照" as UC2
  usecase "訪問者情報更新" as UC3
  usecase "訪問者情報削除" as UC4
}

U1 --> UC1
U1 --> UC2
U1 --> UC3
U1 --> UC4
@enduml